version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DATA_DIR=/app/data
      - EPISODES_DIR=/app/data/episodes

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api 